### ISSUE TITLE
Sampler distorts samples and is mono-only

### ISSUE THREAD

**Issue by jussi-kalliokoski** [jussi-kalliokoski/audiolib.js#1]
Sampler distorts the audio data in it's sample and is currently mono.

**Comment by jussi-kalliokoski** [comment]
https://github.com/jussi-kalliokoski/audiolib.js/commit/969c1384b455970ce45f9cd4bfffdc062bc6a94b Fixed the mono thing, but the distortion remains.

**Comment by jussi-kalliokoski** [comment]
Fixed the NaN-inducing problem in https://github.com/jussi-kalliokoski/audiolib.js/commit/a3a9dc324cbfcd28f046c4934ebf0252b99fa585

**Comment by davidgovea** [comment]
I'll test later today and report back

**Comment by jussi-kalliokoski** [comment]
Great! A more extensive test case could be useful, to hear if the frequencies are actually right, drum samples aren't ideal for that. I'll have to look into that.

But I think I've fixed at least a single case of failure.

**Comment by davidgovea** [comment]
Updated the sampler test to be a bit more helpful.. It generates a 440Hz tone, encodes it with PCMData.encode, and loads it into the Sampler. Pretty sure I set it up right..

It seems like the change you made does correct the pitch, but the note is quite obviously 1/2 the duration of the original.

Will continue testing, I have some time tonight

**Comment by davidgovea** [comment]
Seems like it might be coming from the deinterleave.. each sample seems to be repeated twice in the sampler.samples[0/1] arrays

**Comment by davidgovea** [comment]
Well the deinterleave bug was simple enough - I rolled back your last commit e5b74b8835d96178e8dc as well

PCM encoded / decoded samples in my test are still peaking - just checked, and they seem to be ranged between +-16256 or so.  I probably have the encode/decode process wrong in the test.

However, the direct sampling/resampling test case is working beautifully! :D

**Comment by davidgovea** [comment]
I see.. just needed to change bytesPerSample to 2.
Test is updated - now all the buttons sound the same.

No more clicking in Linux for the drum-sampler test.. still get some on the Mac when there's a lot of voices. Windows, don't know, don't care :P

**Comment by jussi-kalliokoski** [comment]
It seems to be working great, thanks a lot! Also for the test case I said I would do... :D Closing this issue, if something comes up, it's a different issue.
